{
 "title": "jellyfish",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Praia",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"jellyfish\",\n    tag: \"ubicacion\",\n    start: -30d\n)"
    }
   },
   {
    "name": "clima_cod",
    "query": {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"clima_cod\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> last()\n  |> keep(columns: [\"_value\"])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "description": "Map that shows the area affected.",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\" or r[\"_field\"] == \"indice_riesgo\")\n  |> filter(fn: (r) => r[\"ubicacion\"] == \"${Praia}\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Portuguese Skull",
   "type": "text",
   "description": "Drawing of a Portuguese skull.",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 },
   "options": {
    "content": "<img src=\"https://www3.gobiernodecanarias.org/medusa/wiki/images/6/6d/Aguaviva.png\" width=\"75%\">"
   }
  },
  {
   "title": "Portuguese Skull Level",
   "type": "gauge",
   "description": "Estimation of the number of this species. ",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"indice_riesgo\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "description": "Legend for the estimation of the Portuguese Skull.",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 8 },
   "options": {
    "content": "\n🟢 No danger — Optimal conditions for swimming    \n🟡 Low risk — Caution recommended    \n🟠 Risk — Swimming not recommended    \n🔴 High risk — Swimming prohibited"
   }
  },
  {
   "title": "Water Temperature",
   "type": "stat",
   "description": "Water temperature in Celsius.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"temp_agua\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Wave Height",
   "type": "stat",
   "description": "Wave height In meters.",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"altura_olas\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "description": "Forecast with emojis.",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"clima_cod\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "WInd",
   "type": "operato-windrose-panel",
   "description": "Wind speed (m/s)  and direction (cardinal).",
   "gridPos": { "h": 9, "w": 6, "x": 14, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"viento_dir\" or r._field == \"viento_vel\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> pivot(\n      rowKey: [\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> rename(columns: {\n      viento_vel: \"wind_speed\",\n      viento_dir: \"wind_direction\"\n  })"
    }
   ]
  },
  {
   "title": "Date of the data",
   "type": "text",
   "description": "Date when the data were collected.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "options": {
    "content": "\n# ${__from:date:YYYY-MM-DD} || ${__from:date:HH:mm}\n\n"
   }
  },
  {
   "title": "Plankton Level",
   "type": "gauge",
   "description": "Plankton level between 0-1.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jellyfish\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"peligrosidad_medusas\")\n  |> filter(fn: (r) => r._field == \"nivel_plancton\")\n  |> filter(fn: (r) => r.ubicacion == \"${Praia}\")\n  |> last()"
    }
   ]
  }
 ]
}